// testproto 仅为 fieldperm 的黑盒测试提供最小 proto 消息：
// Plan.created_by 的 json_name（createdBy）与 proto 字段名拼写不同，
// 覆盖隐藏集双拼写命中路径；description / remark 两种拼写一致，作保留对照。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: testpb/testproto.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Plan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   *string                `protobuf:"bytes,8,opt,name=description,proto3,oneof" json:"description,omitempty"`                // 两种拼写一致
	Remark        *string                `protobuf:"bytes,9,opt,name=remark,proto3,oneof" json:"remark,omitempty"`                          // 两种拼写一致
	CreatedBy     *uint32                `protobuf:"varint,20,opt,name=created_by,json=createdBy,proto3,oneof" json:"created_by,omitempty"` // json_name = createdBy
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plan) Reset() {
	*x = Plan{}
	mi := &file_testpb_testproto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_testproto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_testpb_testproto_proto_rawDescGZIP(), []int{0}
}

func (x *Plan) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Plan) GetRemark() string {
	if x != nil && x.Remark != nil {
		return *x.Remark
	}
	return ""
}

func (x *Plan) GetCreatedBy() uint32 {
	if x != nil && x.CreatedBy != nil {
		return *x.CreatedBy
	}
	return 0
}

var File_testpb_testproto_proto protoreflect.FileDescriptor

const file_testpb_testproto_proto_rawDesc = "" +
	"\n" +
	"\x16testpb/testproto.proto\x12\x13fieldperm.testproto\"\x98\x01\n" +
	"\x04Plan\x12%\n" +
	"\vdescription\x18\b \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1b\n" +
	"\x06remark\x18\t \x01(\tH\x01R\x06remark\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_by\x18\x14 \x01(\rH\x02R\tcreatedBy\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_remarkB\r\n" +
	"\v_created_byB,Z*github.com/tx7do/go-utils/fieldperm/testpbb\x06proto3"

var (
	file_testpb_testproto_proto_rawDescOnce sync.Once
	file_testpb_testproto_proto_rawDescData []byte
)

func file_testpb_testproto_proto_rawDescGZIP() []byte {
	file_testpb_testproto_proto_rawDescOnce.Do(func() {
		file_testpb_testproto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testpb_testproto_proto_rawDesc), len(file_testpb_testproto_proto_rawDesc)))
	})
	return file_testpb_testproto_proto_rawDescData
}

var file_testpb_testproto_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_testpb_testproto_proto_goTypes = []any{
	(*Plan)(nil), // 0: fieldperm.testproto.Plan
}
var file_testpb_testproto_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testpb_testproto_proto_init() }
func file_testpb_testproto_proto_init() {
	if File_testpb_testproto_proto != nil {
		return
	}
	file_testpb_testproto_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testpb_testproto_proto_rawDesc), len(file_testpb_testproto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testpb_testproto_proto_goTypes,
		DependencyIndexes: file_testpb_testproto_proto_depIdxs,
		MessageInfos:      file_testpb_testproto_proto_msgTypes,
	}.Build()
	File_testpb_testproto_proto = out.File
	file_testpb_testproto_proto_goTypes = nil
	file_testpb_testproto_proto_depIdxs = nil
}
