// testlog 仅为 auditutil 的哈希/签名测试提供最小 proto 消息，
// 字段与审计日志的防篡改约定保持同名（log_hash/signature）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: testpb/testlog.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      uint32                 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LogHash       *string                `protobuf:"bytes,15,opt,name=log_hash,json=logHash,proto3,oneof" json:"log_hash,omitempty"`
	Signature     []byte                 `protobuf:"bytes,16,opt,name=signature,proto3,oneof" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestLog) Reset() {
	*x = TestLog{}
	mi := &file_testpb_testlog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestLog) ProtoMessage() {}

func (x *TestLog) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_testlog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestLog.ProtoReflect.Descriptor instead.
func (*TestLog) Descriptor() ([]byte, []int) {
	return file_testpb_testlog_proto_rawDescGZIP(), []int{0}
}

func (x *TestLog) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *TestLog) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TestLog) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *TestLog) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TestLog) GetLogHash() string {
	if x != nil && x.LogHash != nil {
		return *x.LogHash
	}
	return ""
}

func (x *TestLog) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_testpb_testlog_proto protoreflect.FileDescriptor

const file_testpb_testlog_proto_rawDesc = "" +
	"\n" +
	"\x14testpb/testlog.proto\x12\x10auditutil.testpb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf0\x01\n" +
	"\aTestLog\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\rR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1e\n" +
	"\blog_hash\x18\x0f \x01(\tH\x00R\alogHash\x88\x01\x01\x12!\n" +
	"\tsignature\x18\x10 \x01(\fH\x01R\tsignature\x88\x01\x01B\v\n" +
	"\t_log_hashB\f\n" +
	"\n" +
	"_signatureB,Z*github.com/tx7do/go-utils/auditutil/testpbb\x06proto3"

var (
	file_testpb_testlog_proto_rawDescOnce sync.Once
	file_testpb_testlog_proto_rawDescData []byte
)

func file_testpb_testlog_proto_rawDescGZIP() []byte {
	file_testpb_testlog_proto_rawDescOnce.Do(func() {
		file_testpb_testlog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testpb_testlog_proto_rawDesc), len(file_testpb_testlog_proto_rawDesc)))
	})
	return file_testpb_testlog_proto_rawDescData
}

var file_testpb_testlog_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_testpb_testlog_proto_goTypes = []any{
	(*TestLog)(nil),               // 0: auditutil.testpb.TestLog
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_testpb_testlog_proto_depIdxs = []int32{
	1, // 0: auditutil.testpb.TestLog.created_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_testpb_testlog_proto_init() }
func file_testpb_testlog_proto_init() {
	if File_testpb_testlog_proto != nil {
		return
	}
	file_testpb_testlog_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testpb_testlog_proto_rawDesc), len(file_testpb_testlog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testpb_testlog_proto_goTypes,
		DependencyIndexes: file_testpb_testlog_proto_depIdxs,
		MessageInfos:      file_testpb_testlog_proto_msgTypes,
	}.Build()
	File_testpb_testlog_proto = out.File
	file_testpb_testlog_proto_goTypes = nil
	file_testpb_testlog_proto_depIdxs = nil
}
